enum HOME_ACTION_TYPES {
  IS_LOADING = 'IS_LOADING',
  FETCH_CUSTOMER = 'FETCH_CUSTOMER',
  ADD_CUSTOMER = 'ADD_CUSTOMER',
  EDIT_CUSTOMER = 'EDIT_CUSTOMER',
  DELETE_CUSTOMER = 'DELETE_CUSTOMER',
  SET_SEARCH_KEY = 'SET_SEARCH_KEY',
  SET_PAGINATION = 'SET_PAGINATION',
}

export default HOME_ACTION_TYPES;
